### ISSUE TITLE
Wrong entry , not able to delete

### ISSUE THREAD

**Issue by bondskin** [kevinkub/scriptdu.de#10]
Hi, I made a mistake and created a faulty script in ScriptDude. 
How can I delete the entry?
![image](https://user-images.githubusercontent.com/55050117/109397128-6e8e9e00-7935-11eb-8ea9-06fc907924c3.jpeg)

**Comment by kevinkub** [comment]
You can just delete the script via the regular Scriptable app. Alternatively you can delete via the iOS Files app. Let me know if you have any trouble with that.

**Comment by bondskin** [comment]
Hi @kevinkub, my problem is that the Scriptable does not see this script, hence I cannot delete it.
I also checked the iCloud Drive folder but there is no ".js" file or folder.
I also deleted ScriptDude and re-installed but, but no luck either

**Comment by FelixJongleur42** [comment]
I have the same problem - deleted the js from iCloud / Files and ScriptDude still sees some phantom script.
